version: '3.8'

services:
  db:
    build: ./db
    container_name: birthday_reminder_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/apply_migrations.sh:/apply_migrations.sh
      - ./db/migrations:/migrations
      - ./db/seed-data:/seed-data
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
